version: '3.8'
services:
  db:
    container_name: mysqldb-csv
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csvDB
      MYSQL_USER: user
      MYSQL_PASSWORD: root

    ports:
      - '3307:3306'
volumes:
  db_data: { }